#!/bin/bash

__sourcefilename__=$1
__inputfilename__=$2
__outputfilename__=$3
__newlogfilename__=$4
__logFilter__=./LogFilter
__logfilename__=DEBUG_TOOL_WITH_LOG_logfile
__expectscript__=script.exp

expect ${__expectscript__} ${__sourcefilename__} ${__inputfilename__} ${__outputfilename__}

dos2unix ${__logfilename__}

${__logFilter__} ${__logfilename__} ${__newlogfilename__}

rm ${__logfilename__}

