#!/bin/bash

__sourcepath__=$1
__inputpath__=$2
__outputpath__=$3
__logfilepath__=$4

SOURCEFILELIST=`ls $__sourcepath__`
INPUTFILELIST=`ls $__inputpath__`



for sourcefile in ${SOURCEFILELIST} ; 
do
    for inputfile in ${INPUTFILELIST} ;
    do
        outputfile=${__outputpath__}${sourcefile}_for_${inputfile}.out
        logfile=${__logfilepath__}${sourcefile}_for_${inputfile}.log
        echo "---------------"
        echo $sourcefile
        echo $inputfile
        echo $outputfile
        echo $logfile
        echo $__outputpath__
        echo "---------------"
        bash auto-debug $sourcefile $inputfile $outputfile $logfile
    done
done
